# Establece la imagen base
FROM node:14-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el package.json y el package-lock.json al directorio de trabajo
COPY ./ga-app/package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia los archivos de la aplicación al directorio de trabajo del contenedor
COPY ./ga-app .

# Compila la aplicación de React (si es necesario)
RUN npm run build

# Expone el puerto 80 para que el servidor HTTP pueda escuchar las solicitudes
EXPOSE 80

# Ejecuta el servidor HTTP para servir la aplicación React
CMD ["npm", "start"]
