FROM ubuntu:latest AS builder

# Move to working directory (/build).
WORKDIR /app

# Install compiler and rabbitmq
RUN apt-get update && \
    apt-get -y install build-essential && \
    apt-get -y install librabbitmq-dev

# Copy and download dependency using go mod.
COPY . /app

# Set necessary environment variables needed for our image and build the consumer.
ENV RABBITMQPATH=/usr/include:/usr/lib
ENV LD_LIBRARY_PATH=$RABBITMQPATH:"/usr/local/lib":"/app/lib"
RUN  cd /app && cp .Makefile Makefile && make build

# FROM scratch

# Command to run when starting the container.
ENTRYPOINT ["/app/bld//sender"]