version: "3.9"

services:

  # Create service with message consumer.
  consumer:
    container_name: process_data
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - dev-network
    depends_on:
      - sender
      - message-broker

# Necesito saber mas sobre este punto.
networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge
